### ISSUE TITLE
Best way to reach out to Mentors?

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#36] opened 2015-08-08 06:59 UTC
In the past I've just @ ("at-ed") all the previous mentors that have said they would mentor for meetups.  
I'm not sure this is the best way, as trying to dig back and find those is a chore... and might be a bit rude? (as it makes you follow a thread)

With the idea to build out the website at nodeschool.io/seattle perhaps we could have a self signup section that adds people who sign up to a email list that organizers and mentors could then use to communicate with eachother. (I must admit, That's easier said than done for me... other than creating a google group way back when I'm not sure what's the _"best way"_ to achieve that)

What does everyone think?

**Comment by stuartpb** [comment] 2015-08-10 10:18
Isn't there already a Gitter room?

**Comment by strugee** [comment] 2015-08-11 05:56
Yes, but not all of us use Gitter, AFAICT. The room has seemed relatively inactive when I've popped in (which admittedly was only twice or something).

We could use Librelist for mailing lists.

**Comment by stuartpb** [comment] 2015-08-30 22:43
Reposting this from Slack:

alyeung [3:28 PM] 
i am at nodeschool with Josh.

stuartpb [3:28 PM]
Oh narf was that today

stuartpb [3:34 PM] 
GitHub Issues is a totally awful mechanism for organizing these things

stuartpb [3:35 PM]
I see 10 messages about this in my email and my brain goes "oh, noise about that thing that's supposed to happen at some point"

stuartpb [3:38 PM]
because I've been getting an email for everything anybody in the thread says for weeks, and it's all other people saying they might be able to make it, which has zero impact on me, so I learn to tune them out as noise. And it leads to the entire event (and, indeed, the entire repo) registering as noise to me.

stuartpb [3:39 PM]
Which means I miss the high-priority messages I actually *do* care about

alyeung [3:39 PM] 
i add flags to github issues.

stuartpb [3:40 PM] 
The problem isn't that they get lost in the noise in my email, it's that they *are* the noise in my email

stuartpb [3:41 PM]
If there was a way to say "only email me when Seth or Farrin posts an announcement", it wouldn't be a problem

stuartpb [3:42 PM]
but it's either "watch the thread" or "don't watch the thread", and like I said 90% of the stuff in the thread is noise. Which is why Issues is a bad mechanism for this.

**Comment by stuartpb** [comment] 2015-08-30 22:47
One thing we could do is have separate issues for event **announcements** and event **discussion**.

Also, I've been working on a chat platform that would work really well for this - if anybody wants to help me code DingRoll, it'd give us a good opportunity to have a better solution sooner.

**Comment by JustinBeckwith** [comment] 2017-10-10 15:35
Given the age, closing this issue out.  I think for now we're going to roll with GitHub issues, as it's the easiest way to find all of us at the same time :)

**Closed by JustinBeckwith** 2017-10-10 15:35 UTC
Labels: enhancement, help wanted, question
