### ISSUE TITLE
Proposal: Next Seattle Nodeschool event - March 28?

### ISSUE THREAD

**Issue by louisnk** [nodeschool/seattle#12] opened 2015-03-02 19:48 UTC
Hello Nodeschoolers!

Since Saturday's event was undeniably a great success, it would be awesome to keep up the momentum and get another one planned for the end of March.

If I wasn't mistaken, it sounds like IMSHealth would be open to hosting us again (awesome). @blakmatrix  or @sethvincent could one of you reach out to them and ask about the 28th? That would solve the hard part. 

The other key will be getting some monies from somewhere to buy snacks and things, because people love snacks, and I don't know about you but they taste better when somebody else pays. 

I'll work on figuring that out this week, so we can announce whatever option is chosen with the meetup announcement.

Finally, if we're feeling short on attendees or mentors, the SeattleJS and Seattle Node.js meetup groups both have solid mailing lists full of people who'd love to do both.

**Comment by susanev** [comment] 2015-03-02 19:58
Why not just encourage attendees to bring food to share with everyone instead of charging money. 

Are people really causing some major problem by not showing up? Meetups in general often have more signups then attendees -- not everyone has extra money to attend and I really like the idea that its basically a group study session, instead of a talk or lecture.

If you really want to start charging money, I highly encourage you to make it a sliding scale fee, and not a requirement to attend.

**Comment by louisnk** [comment] 2015-03-02 20:06
Sorry, I didn't articulate that very well, but this is why we have open discussion!

Of course the $5 (or whatever amount) wouldn't be mandatory, that would ruin the inclusive nature of NodeSchool. My goal would be to encourage people to follow through with their RSVP. Meetups always have more signups than attendees, and in general it's around 60% attendance ratio. 

The problem with poor attendance in my eyes (like the ~40% from Saturday) is some people on the wait-list are eager to come, but honestly believe they'll be turned away. Without explicitly stating it, it's hard to tell everyone to just show up if they really want to come. The reason for the RSVP limit is for the hosts to feel comfortable knowing their space won't be over-crowded and possibly in violation of fire codes.

Knowing that people are committed when they sign up helps organizers with logistics and ensuring enough mentors.

**Comment by louisnk** [comment] 2015-03-02 20:11
On the food note - I love the idea of everyone bringing something to share. I think it would bring people together in more meaningful ways than shared coding struggles.

The only downside I see in terms of organizing is it's impossible to gauge what people will bring, or how much. Worst case scenario would be not enough food, or people with specific dietary restrictions being unsure of what they're looking at. 

I don't have a ton of experience dealing with the food aspect of these things, but from what little I do have I feel like meetups order catering (or pizza) because it's "safer" and more predictable.

**Comment by blakmatrix** [comment] 2015-03-02 21:15
@louisnk I think this is a good Idea, I will reach back out to IMS Health this week. 

I do have reservations about charging, without having a free option for folks that want to attend. The node community for me has always been centralized around a sense of open source and that literally anybody can contribute and make a difference. We might be ok with a suggested donation option, but we should make sure that requiring payment would not be prohibitive to the community we are building. If on the other hand we can't get free space and/or healthy snacks, it'd be ok as that's just necessary to secure space, but to @susanev's note, I like the idea of people treating it as a potluck of sorts, but we should be concerned/aware about any food being dietary inclusive and HEALTHY as well. 

**I'd prefer to improve messaging over charging, even if it is a donation.** If we really wanted donations we could start putting out a donation box at the events for future expenditures. When we organized the last event, we wanted to make sure it was more about the nodeschool students learning in an environment that was low key/pressure, fun, and relaxed. Food was strictly snacks (it isn't about the food), a catalyst of sorts around bringing energy levels up after a giving students about an hour of decent mentoring, and giving people a time to take a break and chat with other attendees. 

In (most) future meetups, We should do more to frame the event as **a space for hanging out and co-learning** rather than *anything super formal & top-down*, to build the node community here in Seattle, one that has been rather lacking in a community orientated way, ones like we see in Oakland, Medellin, Brooklyn, etc. I don't have a problem with more structured events, but there needs to be a community need for it first, run by the community. It's both easy and premature to start anticipating/reacting to the needs of the community without first having a problem in the first place... as it is sometimes said, "`Planning is Guessing`".

We could do more to improve attendance, however, it's unfair to say that it's a problem to be solved now, we just had our second meetup, 30-35/100 showed up, the meetup was also created super far in advance, as far as stats nearly everyone that was on the RSVP (~40 ppl) made it onto the list within the last 2 days (most one day after I sent out an e-mail asking attendees to update their RSVPs). Out of the early sign ups only 15/70 showed, where as most of the RSVP made it, but both sides were lacking.. and a lot of it probably had to do with *the awesome Seattle weather we were having* --I know If I hadn't committed to the date, I'd have been out hiking somewhere, it was absolutely beautiful :) -- So maybe next time don't open the RSVP list til 2 weeks out? Also going forward, maybe trying to commit to the last Saturday of the month will help set a frequency for more people to attend? (though in May it will be the 4th Saturday for the NodeSchool International day.)

Thoughts?

**Comment by ptressel** [comment] 2015-03-02 23:53
@louisnk Be very very cautious with the idea of making this a paid event -- it will change the feeling and character of the event.  Approximately zero people will ever take you up on a "hardship waiver" that they need to ask for -- they'll avoid the embarrassment and do the tutorials by themselves.  If the money is for snacks, don't have snacks.  If the money is just a device to reduce the no-show rate, then look into other methods -- @blakmatrix has a start on this, e.g. don't open RSVPs til close to the event date -- or expect and tolerate the attrition.  It's the food amount that usually drives the need for a good attendance prediction, so if you're not getting food, then a precise count isn't as much needed.

**Comment by louisnk** [comment] 2015-03-03 00:09
@blakmatrix I like it! All the things. I'm getting hung up on thinking of this as a "normal" tech meetup where it is more formal and top down, with an agenda and such. Please /slap in the future. With a salmon, instead of a trout :P

You're 100% right, we don't need to charge or get donations to improve attendance. @ptressel thanks for the input also. I should have just asked for suggestions, rather than giving my own based on limited experience.

**Comment by daveskull81** [comment] 2015-03-03 00:12
I agree with @ptressel. Speaking for myself I am very cautious of meetups that have costs associated with them. Opening up RSVPs closer to event time isn't a bad idea, but don't cut it too close that people are able to move something around if they really want to go. In my opinion food isn't necessary for the vent. I think as long as there are good mentors floating around promoting new ideas and spreading their knowledge we can create a great Node community here in Seattle.
My only major thought would be to increase the frequency. Once a month is good, but is twice a month possible? I know these events take a lot of time to put together, but if a company like IMS Health is willing to donate a space it could be a very attainable goal to meet twice a month on a weeknight. Not having the event on a weekend would probably also help in attendance. Last weekend, many people probably didn't go because of the suddenly great weather. Having it on a weeknight might help with attendance as well.

**Comment by louisnk** [comment] 2015-03-03 00:17
@daveskull81 - I would love to do it more than once a month. I think for people who are serious about learning it's not frequent enough. For people who are casual attendees, having more date options is also nice.

The question then becomes what day/night do you put it on? Going beyond that, how do we reach the broader community and let them know it's going on? There are undoubtedly people working with JS on the frontend, or with other languages, who would love to come to NodeSchool but haven't heard about it. What are good avenues for expansion (and assimilation)? :)

**Comment by blakmatrix** [comment] 2015-03-03 00:24
@sethvincent What do you think the chances are that we could use the HUB, on say, every second thursday for a smaller nodeschool?

**Comment by sethvincent** [comment] 2015-03-03 00:30
We'd most likely need to pay for the room (or find a sponsor to pay), but it's possible. All the different rooms can be found here: http://impacthubseattle.com/reservations 

Also it would be cool to do it on a day other than Thursdays since the Code for Seattle weekly meetup is that day. Or I just wouldn't be able to help out with nodeschool on Thursdays.

**Comment by daveskull81** [comment] 2015-03-03 00:31
@louisnk @blakmatrix  I have noticed that most meetups tend to occur in the middle of the week on Tuesday, Wednesday, or Thursday. I know that for myself, Wednesday nights are best. I usually see the meetups that happen on Tuesday or Wednesday have the most people attend them.
AS for getting the word out, we can continue with using Meetup.com as well as other forms of social media. Plus, telling everyone we know. I told a friend of mine about the workshop on Saturday afterwards and he is really excited to come to the next one.

**Comment by susanev** [comment] 2015-03-03 00:38
If you are able to do 2x a month, it would probably be best to do one weekend and one weekday; for me, I would only be able to attend on a weekend (but maybe I am in the minority).

Also with regards to people bringing food; you could just have a living document where people sign up with what they can bring. If you don't want things like chips and soda just say that in the document. 

Thanks for everyones dedication to building out this group!

**Comment by louisnk** [comment] 2015-03-09 21:49
@sethvincent I think it would be pretty cool to do Mondays? It's not the biggest meetup night, plus it's still almost the weekend :P [SeattleJS Hackers](http://www.meetup.com/seattlejshackers) is every other Monday and gets about the same turnout as it did when run on Wednesdays.

@susanev for more events: I went to the [Tech-Diversified](http://www.meetup.com/Tech-Diversified/) meetup last Thursday, which was probably the single most informative, directed meetup I've been to. It could be cool to coordinate with them on scheduling events, which *could* maybe work out to weekly events, so tons of options for people! (I'll call that a pipe dream for now)

About the food: It sounds like you have experience with this sort of thing. Has the living document thing worked well in the past? How did you create it? (google docs, git issue, etc.)

@daveskull81 I agree about the mid-week meetups being most popular. I think there would be some competition from other JS meetups on Weds/Thurs, so Tuesday might be the best option. I could also be totally wrong, I don't have hard numbers to back that up, other than looking at my Meetup calendar for upcoming SeattleJS, Node, etc. events.

@blakmatrix I think there are lots of companies who would be open to hosting us for free on a given weeknight, I'll talk with the organizers of SeattleJS and a couple others to see if they will share some contacts on that front.

**Comment by blakmatrix** [comment] 2015-03-13 06:26
We have confirmed Event space thanks to IMS Health!

**Closed by blakmatrix** 2015-03-13 06:26 UTC
Labels: help wanted
